# ========================= TOP PEOPLE

prefix mtp: <http://w3id.org/polifonia/ontology/meetups-ontology#>
 
select ( count( ?participant) as ?num_people ) ?participant
from <http://data.open.ac.uk/context/meetups>
where
{ VALUES ?subject { <http://dbpedia.org/resource/Edward_Elgar> }
  ?s rdf:type mtp:Meetup ;
      mtp:hasSubject ?subject ;
      mtp:hasParticipant ?participant .
  FILTER  (!regex (str(?participant), str(?subject) ) ) .
}
 
GROUP BY ?participant
ORDER BY DESC(?num_people) ?participant
LIMIT 2

# ========================= TOP PLACES
prefix mtp: <http://w3id.org/polifonia/ontology/meetups-ontology#>
select ( count( ?place) as ?number_place ) ?place
from <http://data.open.ac.uk/context/meetups>
where
{ ?s rdf:type mtp:Meetup ;
      mtp:hasSubject <http://dbpedia.org/resource/Edward_Elgar> ;
      mtp:hasPlace ?place .
}
 
GROUP BY ?place
ORDER BY DESC(?number_place)
LIMIT 2


# ========================= TOP TIME




# ========================= TOP THEMES
prefix mtp: <http://w3id.org/polifonia/ontology/meetups-ontology#>
select ( count( ?meetupType) as ?number_mt ) ?meetupType
from <http://data.open.ac.uk/context/meetups>
where
{ ?s rdf:type mtp:Meetup ;
      mtp:hasSubject <http://dbpedia.org/resource/Edward_Elgar> ;
      mtp:hasAPurpose ?meetupType .
  #?meetupType rdfs:label ?meetupTypeName .
}
 
GROUP BY ?meetupType
ORDER BY DESC(?number_mt)